import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1763351406422 implements MigrationInterface {
    name = 'Auto1763351406422'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."vouchers_discount_type_enum" AS ENUM('percent', 'fixed')`);
        await queryRunner.query(`CREATE TABLE "vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "code" character varying(50) NOT NULL, "discount_type" "public"."vouchers_discount_type_enum" NOT NULL, "discount_value" numeric(10,2) NOT NULL, "min_order_value" numeric(10,2), "max_uses" integer, "uses_count" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "UQ_efc30b2b9169e05e0e1e19d6dd6" UNIQUE ("code"), CONSTRAINT "PK_ed1b7dd909a696560763acdbc04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "name" character varying NOT NULL, "description" text, "permissions" jsonb, "parent_role_id" uuid, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "name" character varying(255) NOT NULL, "address" text NOT NULL, "phone" character varying(20) NOT NULL, "manager_user_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "username" character varying, "password" character varying, "fullName" character varying NOT NULL, "role_id" uuid NOT NULL, "store_id" uuid, "allowed_ips" text array, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_450a05c0c4de5b75ac8d34835b9" UNIQUE ("password"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "user_id" uuid NOT NULL, "token" text NOT NULL, "ip_address" character varying(45) NOT NULL, "device_info" jsonb, "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "parent_id" uuid, "description" text, "image_url" character varying(255), "level" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "name" character varying(255) NOT NULL, "description" text NOT NULL, "category_id" uuid NOT NULL, "base_price" numeric(10,2) NOT NULL, "sku" character varying(50) NOT NULL, "images" jsonb, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "product_id" uuid NOT NULL, "size" character varying(50), "color" character varying(50), "additional_price" numeric(10,2) NOT NULL DEFAULT '0', "stock_quantity" integer NOT NULL DEFAULT '0', "sku" character varying(50) NOT NULL, "images" jsonb, CONSTRAINT "UQ_46f236f21640f9da218a063a866" UNIQUE ("sku"), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_inventories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "store_id" uuid NOT NULL, "variant_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "last_updated" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1d898446c9414646955719315e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."promotions_type_enum" AS ENUM('sale', 'flash_sale', 'bundle')`);
        await queryRunner.query(`CREATE TYPE "public"."promotions_discount_type_enum" AS ENUM('percent', 'fixed')`);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "name" character varying(255) NOT NULL, "type" "public"."promotions_type_enum" NOT NULL, "discount_type" "public"."promotions_discount_type_enum" NOT NULL, "discount_value" numeric(10,2) NOT NULL, "min_order_value" numeric(10,2), "start_date" TIMESTAMP NOT NULL, "end_date" TIMESTAMP NOT NULL, "applicable_stores" bigint array, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "product_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "value" character varying(255) NOT NULL, CONSTRAINT "PK_4fa18fc5c893cb9894fc40ca921" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "email" character varying(255) NOT NULL, "password" character varying(255), "points" integer NOT NULL DEFAULT '0', "voucher_codes" text array, "is_verified" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_34ba886399103660d8af64e3b31" UNIQUE ("email"), CONSTRAINT "PK_814e5a9128d2a2fffbddffc0a27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customer_profiles_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TABLE "customer_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "customer_account_id" uuid NOT NULL, "full_name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "birthday" date, "gender" "public"."customer_profiles_gender_enum", "default_address_id" integer, "preferences" jsonb, "avatar" character varying NOT NULL, CONSTRAINT "REL_815a9332ab816f3abb2d0b6600" UNIQUE ("customer_account_id"), CONSTRAINT "PK_ece08ee55cbe707d9f870907727" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "customer_profile_id" uuid NOT NULL, "street" character varying(255) NOT NULL, "city" character varying(100) NOT NULL, "province" character varying(100) NOT NULL, "country" character varying(100) NOT NULL DEFAULT 'Vietnam', "zip_code" character varying(20), "is_default" boolean NOT NULL DEFAULT false, "recipient_name" character varying(255), "phone" character varying(20), CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "order_id" uuid NOT NULL, "variant_id" uuid NOT NULL, "quantity" integer NOT NULL, "price_at_purchase" numeric(10,2) NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_status_enum" AS ENUM('paid', 'pending')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "customer_account_id" uuid, "total_amount" numeric(10,2) NOT NULL, "discount_applied" numeric(10,2) NOT NULL DEFAULT '0', "is_gift" boolean NOT NULL DEFAULT false, "gift_message" text, "gift_recipient_info" jsonb, "shipping_address_id" uuid NOT NULL, "payment_method" character varying(50) NOT NULL, "payment_status" "public"."orders_payment_status_enum" NOT NULL DEFAULT 'pending', "store_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "order_id" uuid NOT NULL, "status_from" character varying(50) NOT NULL, "status_to" character varying(50) NOT NULL, "note" text, "user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fb7850e731ffae56f7b7d4fad0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "parent_id" uuid, "description" text, "image_url" character varying(255), "level" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_403bbbcee68e1faec9c258beb56" UNIQUE ("slug"), CONSTRAINT "PK_20eed6c3ae534e7721fa44874a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "title" character varying(255) NOT NULL, "content" text NOT NULL, "category_id" uuid NOT NULL, "author_user_id" uuid NOT NULL, "images" jsonb, "publish_date" TIMESTAMP, "is_published" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_39a43dfcb6007180f04aff2357e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "news_id" uuid NOT NULL, "customer_account_id" uuid, "content" text NOT NULL, CONSTRAINT "PK_e9a9bb29efbad7bf25b4434fba2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "variant_id" uuid NOT NULL, "store_id" uuid, "quantity_change" integer NOT NULL, "reason" character varying(255) NOT NULL, "user_id" uuid, CONSTRAINT "PK_06b444680ab11eb7c7d0ed6eced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customer_vouchers_discount_type_enum" AS ENUM('percent', 'fixed')`);
        await queryRunner.query(`CREATE TABLE "customer_vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "customer_account_id" uuid NOT NULL, "code" character varying(50) NOT NULL, "discount_type" "public"."customer_vouchers_discount_type_enum" NOT NULL, "discount_value" numeric(10,2) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, CONSTRAINT "UQ_3ec3c5b60523e867b2e28e8961e" UNIQUE ("code"), CONSTRAINT "PK_ae417e91ab934d36629f77ce065" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer_point_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "customer_account_id" uuid NOT NULL, "points_change" integer NOT NULL, "reason" character varying(255) NOT NULL, "order_id" uuid, CONSTRAINT "PK_d2683c0aa1c6273d36b348455f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "cart_id" uuid NOT NULL, "variant_id" uuid NOT NULL, "quantity" integer NOT NULL, "price_at_add" numeric(10,2) NOT NULL, CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "customer_account_id" uuid, "guest_token" character varying(255), "total_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_items" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'active', "user_id" uuid, "action" character varying(100) NOT NULL, "entity_id" integer NOT NULL, "old_value" jsonb, "new_value" jsonb, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_promotions" ("promotion_id" uuid NOT NULL, "product_id" uuid NOT NULL, CONSTRAINT "PK_e4b44022a78f91401e960df5fc1" PRIMARY KEY ("promotion_id", "product_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f172d00c730ca8aeeb377846de" ON "product_promotions" ("promotion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c543a540feaa54216f5880ab9d" ON "product_promotions" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "category_promotions" ("promotion_id" uuid NOT NULL, "category_id" uuid NOT NULL, CONSTRAINT "PK_68618d91f194af29b6373a6b71e" PRIMARY KEY ("promotion_id", "category_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63e52f9681139ea7c52d3aaeab" ON "category_promotions" ("promotion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ef6654fdb87d970264a7a3891" ON "category_promotions" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_2c6e71b96bff7b9230de9dda83b" FOREIGN KEY ("parent_role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_d7bfb604d471578a260b4eb7bc5" FOREIGN KEY ("manager_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_98a52595c9031d60f5c8d280ca4" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_inventories" ADD CONSTRAINT "FK_42e48b3a30d76893330633d34ad" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_inventories" ADD CONSTRAINT "FK_412cec2b405f6c92fa96f24e729" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attributes" ADD CONSTRAINT "FK_f5a6700abd0494bae3032cf5bbd" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ADD CONSTRAINT "FK_815a9332ab816f3abb2d0b6600d" FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_181bb18253f9a925f63006651db" FOREIGN KEY ("customer_profile_id") REFERENCES "customer_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_db2d0ea722e16e0fe8ab3bce111" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_aaf719c49246f11e7001904819a" FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_67b8be57fc38bda573d2a8513ec" FOREIGN KEY ("shipping_address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_logs" ADD CONSTRAINT "FK_03afb74d68d64c9d3271bcd7012" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_logs" ADD CONSTRAINT "FK_d61beeea5db1e0e1910a6266384" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_categories" ADD CONSTRAINT "FK_d95fa89a24aac2a9120b5409f10" FOREIGN KEY ("parent_id") REFERENCES "news_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news" ADD CONSTRAINT "FK_aac53a9364896452e463139e4a0" FOREIGN KEY ("category_id") REFERENCES "news_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news" ADD CONSTRAINT "FK_387ba23acf21121b55722657249" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_comments" ADD CONSTRAINT "FK_466e90d3eddd050ce396916f564" FOREIGN KEY ("news_id") REFERENCES "news"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_comments" ADD CONSTRAINT "FK_ff2e5ca9bc38a032668545958f2" FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD CONSTRAINT "FK_5132c139264f494991a44453746" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD CONSTRAINT "FK_e2fe6baebaf7cf2c7ec32be4612" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD CONSTRAINT "FK_0786e7b41f2c50ecf588cbd1df6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_vouchers" ADD CONSTRAINT "FK_f226e2a5ad57bbc2fa130787445" FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_point_transactions" ADD CONSTRAINT "FK_d85e576d31e8f967ce9f966ba70" FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_point_transactions" ADD CONSTRAINT "FK_366239e9ed4861034ac2662889e" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_6385a745d9e12a89b859bb25623" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_ede780fc2b865d1d1323e598038" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_1c4fcb55d07fa66cbc334f9bee9" FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_promotions" ADD CONSTRAINT "FK_f172d00c730ca8aeeb377846dee" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_promotions" ADD CONSTRAINT "FK_c543a540feaa54216f5880ab9d6" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_promotions" ADD CONSTRAINT "FK_63e52f9681139ea7c52d3aaeabb" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_promotions" ADD CONSTRAINT "FK_0ef6654fdb87d970264a7a38910" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "category_promotions" DROP CONSTRAINT "FK_0ef6654fdb87d970264a7a38910"`);
        await queryRunner.query(`ALTER TABLE "category_promotions" DROP CONSTRAINT "FK_63e52f9681139ea7c52d3aaeabb"`);
        await queryRunner.query(`ALTER TABLE "product_promotions" DROP CONSTRAINT "FK_c543a540feaa54216f5880ab9d6"`);
        await queryRunner.query(`ALTER TABLE "product_promotions" DROP CONSTRAINT "FK_f172d00c730ca8aeeb377846dee"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_1c4fcb55d07fa66cbc334f9bee9"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_ede780fc2b865d1d1323e598038"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_6385a745d9e12a89b859bb25623"`);
        await queryRunner.query(`ALTER TABLE "customer_point_transactions" DROP CONSTRAINT "FK_366239e9ed4861034ac2662889e"`);
        await queryRunner.query(`ALTER TABLE "customer_point_transactions" DROP CONSTRAINT "FK_d85e576d31e8f967ce9f966ba70"`);
        await queryRunner.query(`ALTER TABLE "customer_vouchers" DROP CONSTRAINT "FK_f226e2a5ad57bbc2fa130787445"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP CONSTRAINT "FK_0786e7b41f2c50ecf588cbd1df6"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP CONSTRAINT "FK_e2fe6baebaf7cf2c7ec32be4612"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP CONSTRAINT "FK_5132c139264f494991a44453746"`);
        await queryRunner.query(`ALTER TABLE "news_comments" DROP CONSTRAINT "FK_ff2e5ca9bc38a032668545958f2"`);
        await queryRunner.query(`ALTER TABLE "news_comments" DROP CONSTRAINT "FK_466e90d3eddd050ce396916f564"`);
        await queryRunner.query(`ALTER TABLE "news" DROP CONSTRAINT "FK_387ba23acf21121b55722657249"`);
        await queryRunner.query(`ALTER TABLE "news" DROP CONSTRAINT "FK_aac53a9364896452e463139e4a0"`);
        await queryRunner.query(`ALTER TABLE "news_categories" DROP CONSTRAINT "FK_d95fa89a24aac2a9120b5409f10"`);
        await queryRunner.query(`ALTER TABLE "order_logs" DROP CONSTRAINT "FK_d61beeea5db1e0e1910a6266384"`);
        await queryRunner.query(`ALTER TABLE "order_logs" DROP CONSTRAINT "FK_03afb74d68d64c9d3271bcd7012"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_67b8be57fc38bda573d2a8513ec"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_aaf719c49246f11e7001904819a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_db2d0ea722e16e0fe8ab3bce111"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_181bb18253f9a925f63006651db"`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" DROP CONSTRAINT "FK_815a9332ab816f3abb2d0b6600d"`);
        await queryRunner.query(`ALTER TABLE "product_attributes" DROP CONSTRAINT "FK_f5a6700abd0494bae3032cf5bbd"`);
        await queryRunner.query(`ALTER TABLE "store_inventories" DROP CONSTRAINT "FK_412cec2b405f6c92fa96f24e729"`);
        await queryRunner.query(`ALTER TABLE "store_inventories" DROP CONSTRAINT "FK_42e48b3a30d76893330633d34ad"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_98a52595c9031d60f5c8d280ca4"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_d7bfb604d471578a260b4eb7bc5"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_2c6e71b96bff7b9230de9dda83b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ef6654fdb87d970264a7a3891"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63e52f9681139ea7c52d3aaeab"`);
        await queryRunner.query(`DROP TABLE "category_promotions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c543a540feaa54216f5880ab9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f172d00c730ca8aeeb377846de"`);
        await queryRunner.query(`DROP TABLE "product_promotions"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP TABLE "customer_point_transactions"`);
        await queryRunner.query(`DROP TABLE "customer_vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."customer_vouchers_discount_type_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_logs"`);
        await queryRunner.query(`DROP TABLE "news_comments"`);
        await queryRunner.query(`DROP TABLE "news"`);
        await queryRunner.query(`DROP TABLE "news_categories"`);
        await queryRunner.query(`DROP TABLE "order_logs"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TABLE "customer_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."customer_profiles_gender_enum"`);
        await queryRunner.query(`DROP TABLE "customer_accounts"`);
        await queryRunner.query(`DROP TABLE "product_attributes"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_discount_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_type_enum"`);
        await queryRunner.query(`DROP TABLE "store_inventories"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."vouchers_discount_type_enum"`);
    }

}
